# platform :ios, '9.0'
use_frameworks!

load './ZHMainConfig.rb'

target 'Example' do

#pod 'ZDTestKit', :path => '../'
#pod 'ZDTestKit', :path => '../ZDTestKit.podspec'
#pod 'ZDTestKit', :path => '../ZDTestKit-Lib.podspec'


#pod 'ZDTestKit', :podspec => '../ZDTestKit.podspec'
bc_pod 'ZDTestKit', :git => 'git@github.com:zdq1179169386/ZDTestKit.git', :tag => '0.0.1', :bc_useRemote => 1

end
